services:
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    environment:
      - VITE_API_URL=http://backend:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - petsinmind-net

  backend:
    build: ./backend
    ports: ["8080:8080"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/PetsInMindDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - petsinmind-net

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=vLEBM7XeCqp7F7gk
      - MYSQL_DATABASE=PetsInMindDB
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - petsinmind-net

volumes:
  mysql_data:

networks:
  petsinmind-net:
    external: true
    driver: bridge