name: Deploy Backend to OKD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/petsinmind-backend ./backend


    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/petsinmind-backend

    - name: Install OpenShift CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar -xz
        sudo mv oc /usr/local/bin/

    - name: Log in to OKD
      run: oc login ${{ secrets.OKD_SERVER }} --token=${{ secrets.OKD_TOKEN }} --insecure-skip-tls-verify

    - name: Redeploy on OKD
      run: |
        oc project ${{ secrets.OKD_PROJECT }}
        oc rollout restart deployment/petsinmind-backend
